export const DUTCH_LOCATIONS = [
  "Amsterdam",
  "Rotterdam",
  "Den Haag",
  "Utrecht",
  "Eindhoven",
  "Groningen",
  "Tilburg",
  "Almere",
  "Breda",
  "Nijmegen",
  "Arnhem",
  "Haarlem",
  "Amersfoort",
  "Apeldoorn",
  "Leiden",
  "Dordrecht",
  "Zwolle",
  "Maastricht",
  "Deventer",
  "Den Bosch",
  "Alkmaar",
  "Zaandam",
  "Purmerend",
  "Hilversum",
  "Hoofddorp",
  "Enschede",
  "Hengelo",
  "Amstelveen",
  "Schiedam",
  "Spijkenisse",
  "Lelystad",
  "Helmond",
  "Oss",
  "Venlo",
  "Roosendaal",
  "Zoetermeer",
  // Regio-opties
  "Regio Amsterdam",
  "Regio Utrecht",
  "Regio Rotterdam",
  "Randstad",
] as const;

