import { DUTCH_PROVINCES } from "@/lib/zorenta/regions";

/** Keys: `normalizeCityKey(city)` → province label (must match `DUTCH_PROVINCES`). */
const CITY_TO_PROVINCE_RAW: Record<string, string> = {
  amsterdam: "Noord-Holland",
  haarlem: "Noord-Holland",
  zaandam: "Noord-Holland",
  alkmaar: "Noord-Holland",
  hilversum: "Noord-Holland",
  purmerend: "Noord-Holland",
  hoorn: "Noord-Holland",
  denhelder: "Noord-Holland",
  schagen: "Noord-Holland",
  enkhuizen: "Noord-Holland",
  rotterdam: "Zuid-Holland",
  denhaag: "Zuid-Holland",
  sgravenhage: "Zuid-Holland",
  leiden: "Zuid-Holland",
  delft: "Zuid-Holland",
  zoetermeer: "Zuid-Holland",
  dordrecht: "Zuid-Holland",
  schiedam: "Zuid-Holland",
  vlaardingen: "Zuid-Holland",
  gouda: "Zuid-Holland",
  alphenaandenrijn: "Zuid-Holland",
  spijkenisse: "Zuid-Holland",
  capelleaandenijssel: "Zuid-Holland",
  rijswijk: "Zuid-Holland",
  westland: "Zuid-Holland",
  utrecht: "Utrecht",
  amersfoort: "Utrecht",
  veenendaal: "Utrecht",
  zeist: "Utrecht",
  nieuwegein: "Utrecht",
  eindhoven: "Noord-Brabant",
  tilburg: "Noord-Brabant",
  breda: "Noord-Brabant",
  denbosch: "Noord-Brabant",
  shertogenbosch: "Noord-Brabant",
  helmond: "Noord-Brabant",
  oss: "Noord-Brabant",
  roosendaal: "Noord-Brabant",
  bergenopzoom: "Noord-Brabant",
  uden: "Noord-Brabant",
  waalwijk: "Noord-Brabant",
  venlo: "Limburg",
  maastricht: "Limburg",
  heerlen: "Limburg",
  sittard: "Limburg",
  weert: "Limburg",
  roermond: "Limburg",
  arnhem: "Gelderland",
  nijmegen: "Gelderland",
  apeldoorn: "Gelderland",
  ede: "Gelderland",
  harderwijk: "Gelderland",
  zutphen: "Gelderland",
  doetinchem: "Gelderland",
  tiel: "Gelderland",
  wageningen: "Gelderland",
  groningen: "Groningen",
  emmen: "Drenthe",
  assen: "Drenthe",
  hoogeveen: "Drenthe",
  zwolle: "Overijssel",
  enschede: "Overijssel",
  deventer: "Overijssel",
  almelo: "Overijssel",
  hengelo: "Overijssel",
  kampen: "Overijssel",
  leeuwarden: "Friesland",
  drachten: "Friesland",
  sneek: "Friesland",
  harlingen: "Friesland",
  middelburg: "Zeeland",
  vlissingen: "Zeeland",
  goes: "Zeeland",
  terneuzen: "Zeeland",
  almere: "Flevoland",
  lelystad: "Flevoland",
  emmeloord: "Flevoland",
  maassluis: "Zuid-Holland",
  barendrecht: "Zuid-Holland",
  ridderkerk: "Zuid-Holland",
  papendrecht: "Zuid-Holland",
  sliedrecht: "Zuid-Holland",
  gorinchem: "Zuid-Holland",
  culemborg: "Gelderland",
  venray: "Noord-Brabant",
  kerkrade: "Limburg",
  valkenburg: "Limburg",
  oldenzaal: "Overijssel",
  steenwijk: "Overijssel",
  meppel: "Drenthe",
  roden: "Drenthe",
  veendam: "Groningen",
  stadskanaal: "Groningen",
  winschoten: "Groningen",
  uithuizen: "Groningen",
  texel: "Noord-Holland",
  aalsmeer: "Noord-Holland",
  amstelveen: "Noord-Holland",
  diemen: "Noord-Holland",
  heemstede: "Noord-Holland",
  bloemendaal: "Noord-Holland",
  zandvoort: "Noord-Holland",
  ijmuiden: "Noord-Holland",
  veldhoven: "Noord-Brabant",
  best: "Noord-Brabant",
  oosterhout: "Noord-Brabant",
  boxtel: "Noord-Brabant",
  veghel: "Noord-Brabant",
  cuijk: "Noord-Brabant",
  beuningen: "Gelderland",
  druten: "Gelderland",
  wijchen: "Gelderland",
  heumen: "Gelderland",
  malden: "Gelderland",
  groesbeek: "Gelderland",
  nunspeet: "Gelderland",
  elburg: "Gelderland",
  ermelo: "Gelderland",
  putten: "Gelderland",
  barneveld: "Gelderland",
  scherpenzeel: "Gelderland",
  voorthuizen: "Gelderland",
  houten: "Utrecht",
  ijsselstein: "Utrecht",
  soest: "Utrecht",
  baarn: "Utrecht",
  bilthoven: "Utrecht",
  debilt: "Utrecht",
  breukelen: "Utrecht",
  loenen: "Utrecht",
  maarssen: "Utrecht",
  woerden: "Utrecht",
  montfoort: "Utrecht",
  oudewater: "Utrecht",
  ijsselmuiden: "Overijssel",
  hasselt: "Overijssel",
  staphorst: "Overijssel",
  urk: "Flevoland",
  dronten: "Flevoland",
  zeewolde: "Flevoland",
  huizen: "Noord-Holland",
  naarden: "Noord-Holland",
  bussum: "Noord-Holland",
  weesp: "Noord-Holland",
  volendam: "Noord-Holland",
  edam: "Noord-Holland",
};

const PROVINCE_SET = new Set(DUTCH_PROVINCES as readonly string[]);

function normalizeCityKey(input: string): string {
  return input
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .replace(/['’]/g, "")
    .replace(/\s+/g, "");
}

/**
 * Lightweight NL city → province guess for autofill (no external API).
 * Returns a value from `DUTCH_PROVINCES` when recognized; otherwise null.
 */
export function provinceFromDutchCityName(city: string): string | null {
  const raw = city.trim();
  if (!raw) return null;
  const k1 = normalizeCityKey(raw);
  const hit = CITY_TO_PROVINCE_RAW[k1];
  if (hit && PROVINCE_SET.has(hit)) return hit;
  return null;
}
